on:
  push:
    branches:
      - main
name: Deploy on push on main
jobs:
  deploy-on-prod:
    name: Deploy prod
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: Build Project
      run: |
        npm install
        npm run prod

    - name: SFTP Deploy
      uses: AbleLincoln/push-to-sftp@v1.0
      with:
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          local-dir: './*'
          server-dir: '/var/www/app.oralcorp.com.br/htdocs'
