on:
  push:
    branches:
      - main
    # Enables manually triggering of Workflow with file synchronization option
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"

name: Deploy on push on main
jobs:
  deploy-on-prod:
    name: Deploy prod
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: SFTP Deploy
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: "sftp"
        remote-host: ${{ secrets.SFTP_HOST }}
        remote-user: ${{ secrets.SFTP_USER }}
        remote-password: ${{ secrets.SFTP_PASS }}
        local-path: "/*"
        remote-path: "/var/www/app.oralcorp.com.br/htdocs/"
        sync: "full"
