on:
  push:
    branches:
      - main
name: Deploy on push on main
jobs:
  deploy-on-prod:
    name: Deploy prod
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: SFTP Deploy
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: "sftp"
        remote-host: ${{ secrets.SFTP_HOST }}
        remote-user: ${{ secrets.SFTP_USER }}
        remote-password: ${{ secrets.SFTP_PASS }}
        local-path: "/*"
        remote-path: "/var/www/app.oralcorp.com.br/htdocs/"
